name: Update major version tag
description:
  Update major version tags for GitHub Actions based on semantic versioning tags
author: Joram van den Boezem
inputs:
  github_token:
    description: GitHub token
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
branding:
  icon: tag
  color: red
