name: Update major version tag
description: Update major version tags for GitHub Actions based on semantic versioning tags
author: nownabe
inputs:
  github_token:
    description: GitHub token
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
branding:
  icon: tag
  color: red
